Disable next.js compression to stop error spam
Specifically this spam:
  TypeError: Cannot read properties of undefined (reading 'end')

Root cause was revealed by stack trace:
compression is not available without server target.
See https://nextjs.org/docs/pages/api-reference/next-config-js/compress